{"metadata":{"title":"SignInWithAppleError.invalidCallback","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth20SignInWithAppleErrorO15invalidCallbackyA2CmF"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback"]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidCallback","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A callback has been invoked without a nonce."}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"navigatorTitle":[{"kind":"identifier","text":"SignInWithAppleError"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignInWithAppleError"}],"abstract":[{"type":"text","text":"Errors thrown by "},{"code":"SignInWithAppleHandler","type":"codeVoice"},{"text":" instances.","type":"text"}],"type":"topic","title":"SignInWithAppleError","url":"\/documentation\/rxfireauth\/signinwithappleerror","kind":"symbol","role":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","type":"topic","kind":"symbol","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}],"abstract":[{"text":"A callback has been invoked without a nonce.","type":"text"}],"title":"SignInWithAppleError.invalidCallback","kind":"symbol"}}}