{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback"},"abstract":[{"text":"A callback has been invoked without a nonce.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth20SignInWithAppleErrorO15invalidCallbackyA2CmF","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidCallback","kind":"identifier"}],"title":"SignInWithAppleError.invalidCallback","role":"symbol","roleHeading":"Case"},"kind":"symbol","references":{"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"kind":"symbol","title":"SignInWithAppleError","abstract":[{"type":"text","text":"Errors thrown by "},{"code":"SignInWithAppleHandler","type":"codeVoice"},{"type":"text","text":" instances."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SignInWithAppleError"}],"url":"\/documentation\/rxfireauth\/signinwithappleerror","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInWithAppleError","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","title":"RxFireAuth","type":"topic","abstract":[]},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidCallback","kind":"identifier"}],"title":"SignInWithAppleError.invalidCallback","abstract":[{"type":"text","text":"A callback has been invoked without a nonce."}]}}}