{"metadata":{"role":"symbol","title":"UserError.alreadyAnonymous","roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous"},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"role":"symbol","title":"UserError.alreadyAnonymous","type":"topic","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous"},"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","kind":"symbol","title":"RxFireAuth","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"url":"\/documentation\/rxfireauth\/usererror","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"role":"symbol","title":"UserError","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}]}}}