{"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"sections":[],"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","interfaceLanguage":"swift"},"metadata":{"title":"UserError.alreadyAnonymous","symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","title":"UserError","role":"symbol","type":"topic","navigatorTitle":[{"text":"UserError","kind":"identifier"}],"abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"title":"UserError.alreadyAnonymous","kind":"symbol","url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","role":"symbol","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alreadyAnonymous","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"abstract":[],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","title":"RxFireAuth","url":"\/documentation\/rxfireauth"}}}