{"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","title":"UserError.invalidUpdate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUpdate"}],"roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"symbolKind":"case","role":"symbol"},"abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"url":"\/documentation\/rxfireauth\/usererror","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"title":"UserError","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}],"navigatorTitle":[{"kind":"identifier","text":"UserError"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}],"kind":"symbol","abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/rxfireauth\/usererror\/invalidupdate","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","title":"UserError.invalidUpdate"},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/rxfireauth","title":"RxFireAuth","type":"topic"}}}