{"kind":"article","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"metadata":{"title":"LocalizedError Implementations","modules":[{"name":"RxFireAuth"}],"role":"collectionGroup"},"sections":[],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/failureReason","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/helpAnchor","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/recoverySuggestion"],"title":"Instance Properties","generated":true}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/helpAnchor":{"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror\/helpanchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"type":"topic","title":"helpAnchor","role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/helpAnchor"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/recoverySuggestion":{"role":"symbol","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/recoverySuggestion","url":"\/documentation\/rxfireauth\/usererror\/recoverysuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","title":"recoverySuggestion","abstract":[]},"doc://RxFireAuth/documentation/RxFireAuth":{"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth","role":"collection"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/failureReason":{"title":"failureReason","role":"symbol","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/failureReason","url":"\/documentation\/rxfireauth\/usererror\/failurereason"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"title":"UserError","kind":"symbol","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"role":"symbol","url":"\/documentation\/rxfireauth\/usererror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}],"type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}]}}}