{"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"metadata":{"title":"LocalizedError Implementations","modules":[{"name":"RxFireAuth"}],"role":"collectionGroup"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/failureReason","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/helpAnchor","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/recoverySuggestion"],"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","references":{"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","kind":"symbol","title":"RxFireAuth","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/failureReason":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/rxfireauth\/usererror\/failurereason","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/failureReason","abstract":[],"role":"symbol","kind":"symbol","title":"failureReason","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/recoverySuggestion":{"abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/recoverySuggestion","url":"\/documentation\/rxfireauth\/usererror\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"recoverySuggestion","kind":"symbol","role":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"url":"\/documentation\/rxfireauth\/usererror","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"role":"symbol","title":"UserError","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/helpAnchor":{"url":"\/documentation\/rxfireauth\/usererror\/helpanchor","kind":"symbol","role":"symbol","type":"topic","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/helpAnchor","abstract":[]}}}