{"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"RxFireAuth"}],"title":"LocalizedError Implementations","roleHeading":"API Collection","role":"collectionGroup"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/failureReason","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/helpAnchor","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/recoverySuggestion"],"generated":true}],"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/helpAnchor":{"abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/helpAnchor","title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/rxfireauth\/usererror\/helpanchor","kind":"symbol","role":"symbol","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/failureReason":{"title":"failureReason","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/failureReason","url":"\/documentation\/rxfireauth\/usererror\/failurereason"},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","type":"topic","kind":"symbol","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/recoverySuggestion":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"recoverySuggestion","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/recoverySuggestion","kind":"symbol","url":"\/documentation\/rxfireauth\/usererror\/recoverysuggestion"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"type":"text","text":" implementations."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UserError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror","title":"UserError"}}}