{"metadata":{"modules":[{"name":"RxFireAuth"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"externalID":"s:10RxFireAuth9UserErrorO07networkE0yA2CmF","title":"UserError.networkError","roleHeading":"Case","role":"symbol"},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/networkerror"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","abstract":[{"text":"Errors thrown by  ","type":"text"},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"navigatorTitle":[{"text":"UserError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"title":"UserError","type":"topic","url":"\/documentation\/rxfireauth\/usererror"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/networkError":{"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError","abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"title":"UserError.networkError","type":"topic","url":"\/documentation\/rxfireauth\/usererror\/networkerror"},"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","url":"\/documentation\/rxfireauth","kind":"symbol","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","abstract":[],"role":"collection"}}}