{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/provideralreadylinked"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providerAlreadyLinked"}],"externalID":"s:10RxFireAuth9UserErrorO21providerAlreadyLinkedyA2CmF","modules":[{"name":"RxFireAuth"}],"title":"UserError.providerAlreadyLinked"},"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/providerAlreadyLinked","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The specified provider is already linked with this user."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"providerAlreadyLinked","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"sections":[],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/providerAlreadyLinked":{"abstract":[{"text":"The specified provider is already linked with this user.","type":"text"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/providerAlreadyLinked","url":"\/documentation\/rxfireauth\/usererror\/provideralreadylinked","role":"symbol","kind":"symbol","type":"topic","title":"UserError.providerAlreadyLinked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"providerAlreadyLinked","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","url":"\/documentation\/rxfireauth","kind":"symbol","title":"RxFireAuth","role":"collection","abstract":[]},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","url":"\/documentation\/rxfireauth\/usererror","role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}],"abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"type":"text","text":" implementations."}],"title":"UserError","navigatorTitle":[{"kind":"identifier","text":"UserError"}],"kind":"symbol"}}}