{"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/userNotFound","interfaceLanguage":"swift"},"abstract":[{"text":"The specified user cannot be found.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"userNotFound","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/usernotfound"]}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userNotFound","kind":"identifier"}],"externalID":"s:10RxFireAuth9UserErrorO12userNotFoundyA2CmF","roleHeading":"Case","role":"symbol","symbolKind":"case","modules":[{"name":"RxFireAuth"}],"title":"UserError.userNotFound"},"sections":[],"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"abstract":[],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","title":"RxFireAuth","url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/userNotFound":{"title":"UserError.userNotFound","url":"\/documentation\/rxfireauth\/usererror\/usernotfound","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The specified user cannot be found."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/userNotFound","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userNotFound"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","title":"UserError","role":"symbol","type":"topic","navigatorTitle":[{"text":"UserError","kind":"identifier"}],"abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}]}}}