{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/RxFireAuth\/SQ","doc:\/\/RxFireAuth\/s5ErrorP","doc:\/\/RxFireAuth\/SH","doc:\/\/RxFireAuth\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","interfaceLanguage":"swift"},"abstract":[{"text":"Errors thrown by ","type":"text"},{"code":"SignInWithAppleHandler","type":"codeVoice"},{"type":"text","text":" instances."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignInWithAppleError"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/rxfireauth\/signinwithappleerror"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken"]},{"title":"Default Implementations","identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations"],"generated":true}],"metadata":{"symbolKind":"enum","modules":[{"name":"RxFireAuth"}],"title":"SignInWithAppleError","roleHeading":"Enumeration","externalID":"s:10RxFireAuth20SignInWithAppleErrorO","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SignInWithAppleError","kind":"identifier"}],"navigatorTitle":[{"text":"SignInWithAppleError","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth"]]},"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","abstract":[],"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/SQ":{"type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/SQ","title":"Swift.Equatable"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Equatable-Implementations":{"type":"topic","kind":"article","url":"\/documentation\/rxfireauth\/signinwithappleerror\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"type":"topic","kind":"symbol","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","title":"SignInWithAppleError.invalidCallback","role":"symbol","abstract":[{"text":"A callback has been invoked without a nonce.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCallback"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"navigatorTitle":[{"text":"SignInWithAppleError","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/rxfireauth\/signinwithappleerror","title":"SignInWithAppleError","role":"symbol","abstract":[{"type":"text","text":"Errors thrown by "},{"type":"codeVoice","code":"SignInWithAppleHandler"},{"text":" instances.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInWithAppleError","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"},"doc://RxFireAuth/SH":{"identifier":"doc:\/\/RxFireAuth\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Error-Implementations":{"type":"topic","kind":"article","url":"\/documentation\/rxfireauth\/signinwithappleerror\/error-implementations","title":"Error Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations"},"doc://RxFireAuth/s5ErrorP":{"identifier":"doc:\/\/RxFireAuth\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://RxFireAuth/s8SendableP":{"identifier":"doc:\/\/RxFireAuth\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidIdToken":{"type":"topic","kind":"symbol","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalididtoken","title":"SignInWithAppleError.invalidIdToken","role":"symbol","abstract":[{"text":"Apple returned an invalid ID token.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidIdToken","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken"}}}