{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"RxFireAuth"}],"role":"symbol","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignInWithAppleError"}],"navigatorTitle":[{"text":"SignInWithAppleError","kind":"identifier"}],"symbolKind":"enum","externalID":"s:10RxFireAuth20SignInWithAppleErrorO","title":"SignInWithAppleError"},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken"]},{"generated":true,"identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/RxFireAuth\/SQ","doc:\/\/RxFireAuth\/s5ErrorP","doc:\/\/RxFireAuth\/SH","doc:\/\/RxFireAuth\/s8SendableP"]}],"variants":[{"paths":["\/documentation\/rxfireauth\/signinwithappleerror"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Errors thrown by ","type":"text"},{"type":"codeVoice","code":"SignInWithAppleHandler"},{"type":"text","text":" instances."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SignInWithAppleError"}],"languages":["swift"]}]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"abstract":[{"type":"text","text":"A callback has been invoked without a nonce."}],"role":"symbol","title":"SignInWithAppleError.invalidCallback","type":"topic","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Equatable-Implementations":{"url":"\/documentation\/rxfireauth\/signinwithappleerror\/equatable-implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations","title":"Equatable Implementations"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"url":"\/documentation\/rxfireauth\/signinwithappleerror","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SignInWithAppleError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignInWithAppleError"}],"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","abstract":[{"text":"Errors thrown by ","type":"text"},{"code":"SignInWithAppleHandler","type":"codeVoice"},{"text":" instances.","type":"text"}],"title":"SignInWithAppleError"},"doc://RxFireAuth/SQ":{"type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/SQ","title":"Swift.Equatable"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidIdToken":{"url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalididtoken","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken","title":"SignInWithAppleError.invalidIdToken","abstract":[{"text":"Apple returned an invalid ID token.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidIdToken","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://RxFireAuth/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/s5ErrorP","title":"Swift.Error"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Error-Implementations":{"kind":"article","title":"Error Implementations","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations","abstract":[],"url":"\/documentation\/rxfireauth\/signinwithappleerror\/error-implementations","role":"collectionGroup","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","url":"\/documentation\/rxfireauth","kind":"symbol","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","abstract":[],"role":"collection"},"doc://RxFireAuth/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/s8SendableP","title":"Swift.Sendable"},"doc://RxFireAuth/SH":{"type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/SH","title":"Swift.Hashable"}}}